spring.application.name=chat


# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5.5

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gpt-oss:20b
#llama3.1



# App

app.ai.model=openai
app.ai.stream.buffer.max-size=100
app.ai.stream.buffer.max-time=500


logging.level.org.springframework.ai=TRACE

