spring.application.name=chat

spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true

spring.jmx.enabled=true


# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5.5

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gpt-oss:20b
#llama3.1


# App
app.ai.model=openai
app.ai.stream.buffer.max-size=100
app.ai.stream.buffer.max-time=500
app.ai.max-input-length=1000


# Weather API
app.weather.api.url=https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,rain,wind_speed_10m


# API Ninjas
app.api-ninjas.api-key=${API_NINJAS_API_KEY}
app.api-ninjas.geocoding.url=https://api.api-ninjas.com/v1/geocoding?city={city}&country={country}
app.api-ninjas.reverse-geocoding.url=https://api.api-ninjas.com/v1/reversegeocoding?lat={latitude}&lon={longitude}


# Logging
logging.level.org.springframework.ai=TRACE

