create table summary (
    id          bigint generated by default as identity primary key,
    text        text not null,
    text_summary text not null
);
create index summary_text_idx on summary (text);
